name: Publish

on:
  release:
    types:
      - created

jobs:
  publish_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install dependencies
      run: npm ci
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

  publish_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install dependencies
      run: npm ci
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

  publish_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4  
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install dependencies
      run: npm ci
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish


